/**
 * Replenishment Parameters for Location API
 * API for Replenishment Parameters functional module related to Location Template You can find out more about Replenishment Parameters Location Template API on related [API Definition](https://oneit.wba.com/confluence/display/RXRNWAPI/Location+Template+-+API+Definition) 
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ServiceResult } from './serviceResult';


export interface LocationAssociationTO {
    /**
     * It is the location association type
     */
    type: LocationAssociationTO.TypeEnum;
    /**
     * For STORE is LocationType, for STORE_GROUP is the StoreGroup Name
     */
    name: string;
    /**
     * For STORE is LocationNumber, for STORE_GROUP is the StoreGroup Number
     */
    code: string;
    serviceResult?: ServiceResult;
}
export namespace LocationAssociationTO {
    export type TypeEnum = 'STORE' | 'STORE_GROUP';
    export const TypeEnum = {
        STORE: 'STORE' as TypeEnum,
        STOREGROUP: 'STORE_GROUP' as TypeEnum
    }
}
