/**
 * Replenishment Parameters for Location API
 * API for Replenishment Parameters functional module related to Location Template You can find out more about Replenishment Parameters Location Template API on related [API Definition](https://oneit.wba.com/confluence/display/RXRNWAPI/Location+Template+-+API+Definition) 
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ServiceResult } from './serviceResult';


export interface LocationIdentifierTO {
    /**
     * The Location Home Store
     */
    locationNumber?: string;
    /**
     * The Location type
     */
    locationType?: LocationIdentifierTO.LocationTypeEnum;
    serviceResult?: ServiceResult;
}
export namespace LocationIdentifierTO {
    export type LocationTypeEnum = 'Pharmacy' | 'Store' | 'HealthcareClinic';
    export const LocationTypeEnum = {
        Pharmacy: 'Pharmacy' as LocationTypeEnum,
        Store: 'Store' as LocationTypeEnum,
        HealthcareClinic: 'HealthcareClinic' as LocationTypeEnum
    }
}
