/**
 * Replenishment Parameters for Location API
 * API for Replenishment Parameters functional module related to Location Template You can find out more about Replenishment Parameters Location Template API on related [API Definition](https://oneit.wba.com/confluence/display/RXRNWAPI/Location+Template+-+API+Definition) 
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocationIdentifierTO } from './locationIdentifierTO';
import { ServiceResult } from './serviceResult';


/**
 * A list of values
 */
export interface LocationTemplateBulkListTO {
    locationList?: Array<LocationIdentifierTO>;
    /**
     * A list of location Group Code
     */
    locationGroupList?: Array<string>;
    templateTypeList?: Array<LocationTemplateBulkListTO.TemplateTypeListEnum>;
    serviceResult?: ServiceResult;
}
export namespace LocationTemplateBulkListTO {
    export type TemplateTypeListEnum = 'ORDERING' | 'OPOL' | 'PREVENT_EXCESS_ORDERS' | 'SUGGESTED_ORDER';
    export const TemplateTypeListEnum = {
        ORDERING: 'ORDERING' as TemplateTypeListEnum,
        OPOL: 'OPOL' as TemplateTypeListEnum,
        PREVENTEXCESSORDERS: 'PREVENT_EXCESS_ORDERS' as TemplateTypeListEnum,
        SUGGESTEDORDER: 'SUGGESTED_ORDER' as TemplateTypeListEnum
    }
}
