/**
 * Replenishment Parameters for Location API
 * API for Replenishment Parameters functional module related to Location Template You can find out more about Replenishment Parameters Location Template API on related [API Definition](https://oneit.wba.com/confluence/display/RXRNWAPI/Location+Template+-+API+Definition) 
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocationAssociationTO } from './locationAssociationTO';
import { OpolParametersLocationTO } from './opolParametersLocationTO';
import { OrderingParametersLocationTO } from './orderingParametersLocationTO';
import { PreventExcessOrdersParametersLocationTO } from './preventExcessOrdersParametersLocationTO';
import { ServiceResult } from './serviceResult';
import { SuggestedOrderParametersLocationTO } from './suggestedOrderParametersLocationTO';


/**
 * A list of values
 */
export interface LocationTemplateTO {
    /**
     * The code related to Template
     */
    code?: string;
    /**
     * It is the template creation date and time
     */
    createdDate?: Date;
    /**
     * It is the template last modified date and time
     */
    lastModifiedDate?: Date;
    /**
     * It is the start date for the template to be active
     */
    startDate: string;
    /**
     * The templateType possible values
     */
    templateType: LocationTemplateTO.TemplateTypeEnum;
    orderingParameters?: OrderingParametersLocationTO;
    opolParameters?: OpolParametersLocationTO;
    preventExcessOrdersParameters?: PreventExcessOrdersParametersLocationTO;
    suggestedOrderParameters?: SuggestedOrderParametersLocationTO;
    /**
     * It is the template level
     */
    level: LocationTemplateTO.LevelEnum;
    locationAssociation?: LocationAssociationTO;
    serviceResult?: ServiceResult;
}
export namespace LocationTemplateTO {
    export type TemplateTypeEnum = 'ORDERING' | 'OPOL' | 'PREVENT_EXCESS_ORDERS' | 'SUGGESTED_ORDER';
    export const TemplateTypeEnum = {
        ORDERING: 'ORDERING' as TemplateTypeEnum,
        OPOL: 'OPOL' as TemplateTypeEnum,
        PREVENTEXCESSORDERS: 'PREVENT_EXCESS_ORDERS' as TemplateTypeEnum,
        SUGGESTEDORDER: 'SUGGESTED_ORDER' as TemplateTypeEnum
    }
    export type LevelEnum = 'STORE' | 'STORE_GROUP' | 'GLOBAL';
    export const LevelEnum = {
        STORE: 'STORE' as LevelEnum,
        STOREGROUP: 'STORE_GROUP' as LevelEnum,
        GLOBAL: 'GLOBAL' as LevelEnum
    }
}
