/**
 * Replenishment Parameters for Location API
 * API for Replenishment Parameters functional module related to Location Template You can find out more about Replenishment Parameters Location Template API on related [API Definition](https://oneit.wba.com/confluence/display/RXRNWAPI/Location+Template+-+API+Definition) 
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReplenishmentParameterTO } from './replenishmentParameterTO';
import { ServiceResult } from './serviceResult';


export interface OpolParametersLocationTO {
    /**
     * How much historical demand to use for Replenishment / integer (format int32)
     */
    historicalDemandPeriod?: ReplenishmentParameterTO;
    /**
     * Check if a Location is candidate for OPOL calculation / boolean (default true)
     */
    calculateOpol?: ReplenishmentParameterTO;
    /**
     * Look for a dispense in specified history to determine whether to calculate OPOL / integer (format int32)
     */
    replenishmentOrderCandidate?: ReplenishmentParameterTO;
    /**
     * Look at item movement, if last movement is a return, then do not calculate OPOL / boolean (default true)
     */
    removeCandidateForReturns?: ReplenishmentParameterTO;
    /**
     * How many weeks to look back for 'Remove Candidate for Returns' Parameter / integer (format int32)
     */
    candidateForReturnsPeriod?: ReplenishmentParameterTO;
    /**
     * Place an override for order period calculated starting from order schedule (example: 1 = 2 , 2 = 2 , 3 = 2 , 4 = 3 , 5 = 5 , 6 = 6 , 7 = 7) / string
     */
    orderPeriodOverride?: ReplenishmentParameterTO;
    /**
     * Format is HH:MM AM/PM (e.g. 3:00 AM) / string
     */
    timeOfOpolGeneration?: ReplenishmentParameterTO;
    serviceResult?: ServiceResult;
}
