/**
 * Replenishment Parameters for Location API
 * API for Replenishment Parameters functional module related to Location Template You can find out more about Replenishment Parameters Location Template API on related [API Definition](https://oneit.wba.com/confluence/display/RXRNWAPI/Location+Template+-+API+Definition) 
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReplenishmentParameterTO } from './replenishmentParameterTO';
import { ServiceResult } from './serviceResult';


export interface PreventExcessOrdersParametersLocationTO {
    /**
     * Excess order cap calculation input - order qty low limit for items with qty of units greater than 1 / integer (format int32)
     */
    yOrderQtyLowLimitUnitsGt1?: ReplenishmentParameterTO;
    /**
     * Excess order cap calculation input - order qty high limit for items with qty of units greater than 1 / integer (format int32)
     */
    zOrderQtyHighLimitUnitsGt1?: ReplenishmentParameterTO;
    /**
     * Excess order cap calculation input - order qty limit for items with qty of units equal to 1 / integer (format int32)
     */
    xOrderQtyLimitUnitEq1?: ReplenishmentParameterTO;
    /**
     * Excess order cap calculation input - order qty limit for items with qty of units equal to 1 / integer (format int32)
     */
    aOrderQtyUsedOrderGtZ?: ReplenishmentParameterTO;
    /**
     * Excess order cap calculation input - PFL order qty limit / integer (format int32)
     */
    qPflOrderLimitQty?: ReplenishmentParameterTO;
    serviceResult?: ServiceResult;
}
