/**
 * Replenishment Parameters for Location API
 * API for Replenishment Parameters functional module related to Location Template You can find out more about Replenishment Parameters Location Template API on related [API Definition](https://oneit.wba.com/confluence/display/RXRNWAPI/Location+Template+-+API+Definition) 
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ServiceResult } from './serviceResult';


export interface ReplenishmentParameterTO {
    /**
     * The Replenishment Parameter template level
     */
    parameterType: ReplenishmentParameterTO.ParameterTypeEnum;
    /**
     * The value of a boolean Replenishment Parameter
     */
    valueBoolean?: boolean;
    /**
     * The value of an integer Replenishment Parameter
     */
    valueInteger?: number;
    /**
     * The value of a string Replenishment Parameter
     */
    valueString?: string;
    serviceResult?: ServiceResult;
}
export namespace ReplenishmentParameterTO {
    export type ParameterTypeEnum = 'CUSTOM' | 'GLOBAL';
    export const ParameterTypeEnum = {
        CUSTOM: 'CUSTOM' as ParameterTypeEnum,
        GLOBAL: 'GLOBAL' as ParameterTypeEnum
    }
}
