/**
 * Replenishment Parameters for Location API
 * API for Replenishment Parameters functional module related to Location Template You can find out more about Replenishment Parameters Location Template API on related [API Definition](https://oneit.wba.com/confluence/display/RXRNWAPI/Location+Template+-+API+Definition) 
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReplenishmentParameterTO } from './replenishmentParameterTO';
import { ServiceResult } from './serviceResult';


export interface SuggestedOrderParametersLocationTO {
    /**
     * Days to consider forward for On Order on Way quantities in Suggested order calculation (including current day) / integer (format int32)
     */
    onHandForwardView?: ReplenishmentParameterTO;
    /**
     * Days to consider backward for On Order on Way quantities in Suggested order calculation (including current day) / integer (format int32)
     */
    onHandBackwardView?: ReplenishmentParameterTO;
    serviceResult?: ServiceResult;
}
