/**
 * Replenishment Parameters for Product Template API
 * API for Replenishment Parameters functional module related to Product Template You can find out more about Replenishment Parameters Product Template API on related [API Definition](https://oneit.wba.com/confluence/display/RXRNWAPI/Product+Template+-+API+Definition). 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReplenishmentParameterTO } from './replenishmentParameterTO';
import { ServiceResult } from './serviceResult';


export interface OpolParametersProductTO {
    /**
     * excludeDemand / boolean (default false)
     */
    excludeDemand?: ReplenishmentParameterTO;
    /**
     * It is the start date related to the exclude period / string (format date)
     */
    excludedDemandPeriodStartDate?: ReplenishmentParameterTO;
    /**
     * It is the end date related to the exclude period / string (format date)
     */
    excludedDemandPeriodEndDate?: ReplenishmentParameterTO;
    serviceResult?: ServiceResult;
}
