/**
 * Replenishment Parameters for Product Template API
 * API for Replenishment Parameters functional module related to Product Template You can find out more about Replenishment Parameters Product Template API on related [API Definition](https://oneit.wba.com/confluence/display/RXRNWAPI/Product+Template+-+API+Definition). 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocationAssociationTO } from './locationAssociationTO';
import { OpolParametersProductTO } from './opolParametersProductTO';
import { OrderingParametersProductTO } from './orderingParametersProductTO';
import { ProductAssociationTO } from './productAssociationTO';
import { RangingParametersProductTO } from './rangingParametersProductTO';
import { ServiceResult } from './serviceResult';


/**
 * A list of values
 */
export interface ProductTemplateTO {
    /**
     * The code related to Template
     */
    code?: string;
    /**
     * It is the template creation date and time
     */
    createdDate?: Date;
    /**
     * It is the last date and time when the Product Template has been modified
     */
    lastModifiedDate?: Date;
    /**
     * It is the start date for the template to be active
     */
    startDate: string;
    /**
     * The templateType possible values
     */
    templateType: ProductTemplateTO.TemplateTypeEnum;
    orderingParameters?: OrderingParametersProductTO;
    rangingParameters?: RangingParametersProductTO;
    opolParameters?: OpolParametersProductTO;
    /**
     * It is the template level
     */
    level: ProductTemplateTO.LevelEnum;
    locationAssociation?: LocationAssociationTO;
    productAssociation: ProductAssociationTO;
    serviceResult?: ServiceResult;
}
export namespace ProductTemplateTO {
    export type TemplateTypeEnum = 'ORDERING' | 'RANGING' | 'OPOL';
    export const TemplateTypeEnum = {
        ORDERING: 'ORDERING' as TemplateTypeEnum,
        RANGING: 'RANGING' as TemplateTypeEnum,
        OPOL: 'OPOL' as TemplateTypeEnum
    }
    export type LevelEnum = 'STORE' | 'STORE_GROUP' | 'GLOBAL';
    export const LevelEnum = {
        STORE: 'STORE' as LevelEnum,
        STOREGROUP: 'STORE_GROUP' as LevelEnum,
        GLOBAL: 'GLOBAL' as LevelEnum
    }
}
