/**
 * Replenishment Parameters for Product Template API
 * API for Replenishment Parameters functional module related to Product Template You can find out more about Replenishment Parameters Product Template API on related [API Definition](https://oneit.wba.com/confluence/display/RXRNWAPI/Product+Template+-+API+Definition). 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductTemplateTO } from './productTemplateTO';
import { ServiceResult } from './serviceResult';


/**
 * A list of values
 */
export interface ProductTemplateListTO {
    /**
     * The total number of elements found
     */
    elementsNumber: number;
    productTemplates: Array<ProductTemplateTO>;
    serviceResult?: ServiceResult;
}
